version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: npr-postgres
    restart: always
    environment:
      POSTGRES_USER: anpr
      POSTGRES_PASSWORD: anpr123
      POSTGRES_DB: anprdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - npr-network


  node-api:
    build: ./node-api
    container_name: npr-node
    restart: always
    volumes:
      - ./node-api/uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - postgres
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - npr-network

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: nginx/Dockerfile
  #   container_name: npr-nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - node-api
  #   networks:
  #     - npr-network


volumes:
  postgres_data:


networks:
  npr-network:
    driver: bridge