const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.MAIL_USER,
    pass: process.env.MAIL_PASS
  }
});

exports.sendWelcomeMail = async (email) => {
  await transporter.sendMail({
    from: `"ANPR System" <${process.env.MAIL_USER}>`,
    to: email,
    subject: "Admin Access Granted — ANPR Surveillance System",
    html: `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Welcome — ANPR System</title>
</head>
<body style="margin:0;padding:0;background-color:#f0f2f5;font-family:'Segoe UI',Arial,sans-serif;">

  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f2f5;padding:32px 0;">
    <tr>
      <td align="center">
        <table width="620" cellpadding="0" cellspacing="0" style="max-width:620px;width:100%;">

          <!-- HEADER -->
          <tr>
            <td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);border-radius:12px 12px 0 0;padding:36px 40px 28px;">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td>
                    <table cellpadding="0" cellspacing="0">
                      <tr>
                        <td style="background:rgba(255,255,255,0.08);border:1px solid rgba(255,255,255,0.15);border-radius:8px;padding:8px 14px;vertical-align:middle;">
                          <span style="font-size:20px;font-weight:800;color:#ffffff;letter-spacing:2px;">ANPR</span>
                          <span style="font-size:10px;color:#a0b4cc;display:block;letter-spacing:3px;margin-top:1px;">SURVEILLANCE SYSTEM</span>
                        </td>
                        <td style="padding-left:14px;vertical-align:middle;">
                          <div style="width:1px;height:36px;background:rgba(255,255,255,0.2);"></div>
                        </td>
                        <td style="padding-left:14px;vertical-align:middle;">
                          <span style="font-size:11px;color:#e63946;font-weight:700;letter-spacing:2px;text-transform:uppercase;display:block;">Aditya Birla Group</span>
                          <span style="font-size:10px;color:#8899aa;letter-spacing:1px;">Secured Premises</span>
                        </td>
                      </tr>
                    </table>
                  </td>
                  <td align="right" style="vertical-align:top;">
                    <span style="background:#2ecc71;color:#fff;font-size:9px;font-weight:700;letter-spacing:2px;padding:4px 10px;border-radius:20px;text-transform:uppercase;">Access Granted</span>
                  </td>
                </tr>
                <tr>
                  <td colspan="2" style="padding-top:24px;">
                    <h1 style="margin:0;color:#ffffff;font-size:22px;font-weight:700;letter-spacing:0.5px;">Welcome, Admin</h1>
                    <p style="margin:6px 0 0;color:#8899bb;font-size:13px;">You have been granted administrative access to the ANPR System.</p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- ACCENT BAR -->
          <tr>
            <td style="background:linear-gradient(90deg,#2ecc71,#1a9e55,#0f3460);height:3px;"></td>
          </tr>

          <!-- BODY -->
          <tr>
            <td style="background:#ffffff;padding:36px 40px 28px;">

              <p style="margin:0 0 6px;color:#444;font-size:14px;">Hello,</p>
              <p style="margin:0 0 24px;color:#555;font-size:14px;line-height:1.75;">
                You have been assigned the role of <strong>Report Review Admin</strong> on the ANPR Surveillance System deployed at <strong>Aditya Birla Group</strong>. 
                You are now authorized to access, review, and manage vehicle detection reports generated by the system.
              </p>

              <!-- Responsibilities Box -->
              <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
                <tr>
                  <td style="background:#f7f9fc;border-left:3px solid #0f3460;border-radius:0 6px 6px 0;padding:16px 20px;">
                    <span style="font-size:11px;font-weight:700;color:#0f3460;letter-spacing:1.5px;text-transform:uppercase;display:block;margin-bottom:10px;">Your Responsibilities</span>
                    <table cellpadding="0" cellspacing="0" width="100%">
                      <tr>
                        <td style="padding:5px 0;font-size:13px;color:#555;">
                          <span style="color:#2ecc71;font-weight:700;margin-right:8px;">&#10003;</span>Review and monitor incoming vehicle detection reports
                        </td>
                      </tr>
                      <tr>
                        <td style="padding:5px 0;font-size:13px;color:#555;">
                          <span style="color:#2ecc71;font-weight:700;margin-right:8px;">&#10003;</span>Verify and validate flagged number plate entries
                        </td>
                      </tr>
                      <tr>
                        <td style="padding:5px 0;font-size:13px;color:#555;">
                          <span style="color:#2ecc71;font-weight:700;margin-right:8px;">&#10003;</span>Take appropriate action on system alerts and incidents
                        </td>
                      </tr>
                      <tr>
                        <td style="padding:5px 0;font-size:13px;color:#555;">
                          <span style="color:#2ecc71;font-weight:700;margin-right:8px;">&#10003;</span>Receive automated daily reports via email
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>

              <!-- CTA Button -->
             

              <p style="margin:0;color:#888;font-size:12px;line-height:1.7;">
                If you believe this access was granted in error, please contact your system administrator immediately. Do not share your credentials with anyone.
              </p>

            </td>
          </tr>

          <!-- DIVIDER -->
          <tr>
            <td style="background:#ffffff;padding:0 40px;">
              <div style="border-top:1px solid #eaecef;"></div>
            </td>
          </tr>

          <!-- FOOTER -->
          <tr>
            <td style="background:#ffffff;border-radius:0 0 12px 12px;padding:20px 40px 28px;">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td style="vertical-align:middle;">
                    <span style="font-size:11px;color:#aaa;display:block;">Deployed at</span>
                    <span style="font-size:13px;font-weight:700;color:#1a1a2e;letter-spacing:0.5px;">Aditya Birla Group</span>
                  </td>
                  <td align="right" style="vertical-align:middle;">
                    <div style="text-align:right;">
                      <span style="font-size:9px;color:#bbb;display:block;letter-spacing:1.5px;text-transform:uppercase;margin-bottom:3px;">Powered by</span>
                      <span style="font-size:13px;font-weight:800;color:#0f3460;letter-spacing:0.5px;">Ampere</span><span style="font-size:13px;font-weight:800;color:#e63946;letter-spacing:0.5px;">Vision</span>
                      <span style="font-size:11px;color:#888;display:block;letter-spacing:0.5px;">Solutions</span>
                    </div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- BOTTOM NOTE -->
          <tr>
            <td align="center" style="padding:16px 0 4px;">
              <p style="margin:0;font-size:11px;color:#aaa;">This is a system-generated email. Please do not reply directly to this message.</p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>

</body>
</html>
    `.trim(),
  });
};