const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.MAIL_USER,
    pass: process.env.MAIL_PASS
  }
});

exports.sendWelcomeMail = async (email) => {
  await transporter.sendMail({
    from: `"ANPR System" <${process.env.MAIL_USER}>`,
    to: email,
    subject: "You've Been Added as a Report Review Admin — ANPR System",
    html: `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Welcome to ANPR System</title>
      </head>
      <body style="margin:0;padding:0;background-color:#f4f6f8;font-family:'Segoe UI',Arial,sans-serif;">
        <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f6f8;padding:40px 0;">
          <tr>
            <td align="center">
              <table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">

                <!-- Header -->
                <tr>
                  <td style="background-color:#1a2b4a;padding:32px 40px;text-align:center;">
                    <h1 style="margin:0;color:#ffffff;font-size:22px;font-weight:600;letter-spacing:1px;text-transform:uppercase;">ANPR System</h1>
                    <p style="margin:6px 0 0;color:#a0b4cc;font-size:13px;letter-spacing:0.5px;">Automated Number Plate Recognition</p>
                  </td>
                </tr>

                <!-- Body -->
                <tr>
                  <td style="padding:40px 40px 32px;">
                    <p style="margin:0 0 16px;font-size:16px;color:#333333;font-weight:600;">Hello,</p>
                    <p style="margin:0 0 20px;font-size:15px;color:#555555;line-height:1.7;">
                      You have been granted <strong style="color:#1a2b4a;">Report Review Admin</strong> access in the ANPR System.
                      As an admin, you are now authorized to review and manage vehicle detection reports generated by the system.
                    </p>

                    <!-- Info Box -->
                    <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0f4fa;border-left:4px solid #1a2b4a;border-radius:4px;margin:24px 0;">
                      <tr>
                        <td style="padding:16px 20px;">
                          <p style="margin:0 0 8px;font-size:13px;font-weight:700;color:#1a2b4a;text-transform:uppercase;letter-spacing:0.5px;">Your Responsibilities Include</p>
                          <ul style="margin:0;padding-left:18px;color:#555555;font-size:14px;line-height:2;">
                            <li>Reviewing incoming vehicle detection reports</li>
                            <li>Verifying flagged number plate entries</li>
                            <li>Taking action on alerts and incidents</li>
                          </ul>
                        </td>
                      </tr>
                    </table>

                    <p style="margin:0 0 28px;font-size:15px;color:#555555;line-height:1.7;">
                      If you believe this was assigned to you in error, or have any questions regarding your role, please contact your system administrator immediately.
                    </p>

                    <!-- CTA Button -->
                    <table cellpadding="0" cellspacing="0">
                      <tr>
                        <td style="background-color:#1a2b4a;border-radius:5px;">
                          <a href="#" style="display:inline-block;padding:12px 28px;color:#ffffff;font-size:14px;font-weight:600;text-decoration:none;letter-spacing:0.3px;">Access the Dashboard →</a>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>

                <!-- Footer -->
                <tr>
                  <td style="background-color:#f9fafb;border-top:1px solid #e8edf2;padding:24px 40px;text-align:center;">
                    <p style="margin:0;font-size:12px;color:#999999;line-height:1.6;">
                      This is an automated notification from the ANPR System.<br/>
                      Please do not reply to this email.
                    </p>
                  </td>
                </tr>

              </table>
            </td>
          </tr>
        </table>
      </body>
      </html>
    `
  });
};